export const fallback = {
  run: {
    id: 'sample', status: 'complete', engagement: 'Muster Verpackungen', fiscal_year: 2025, files: 35, row_count: 32472,
    integrity: 'verified', reported_profit: '2599841.80', proposed_adjusted_profit: '2257041.80',
  },
  metrics: {
    general_ledger_rows: 20258, general_ledger_balance: '0.00', formula_resolved: 47,
    citation_coverage: 100, promoted_findings: 4, unsupported_claims: 0, cleared_signals: 0,
  },
  manifest: [
    { path: 'Kreditoren/Lieferantenbuchungen.txt', kind: 'txt', records: 2584, status: 'parsed' },
    { path: 'Sachkonten/Sachkontobuchungen.txt', kind: 'txt', records: 20258, status: 'parsed' },
    { path: 'Begleitdokumente/Wareneingangsliste_2025.csv', kind: 'csv', records: 858, status: 'parsed' },
    { path: 'Begleitdokumente/Berechtigungsauswertung_2025.xlsx', kind: 'xlsx', status: 'parsed' },
    { path: 'Begleitdokumente/Pruefungsplanung_JET_2025.docx', kind: 'docx', status: 'parsed' },
  ],
  evidence: {
    'ev-change': { id: 'ev-change', file: 'Begleitdokumente/Stammdatenaenderungen_2025.csv', kind: 'row', locator: { row: 8 }, label: 'Self-approved vendor creation', excerpt: '12.05.2025 · 209101 · Ratio Consulting GmbH · changed by MV-U05 · approved by MV-U05', sha256: '6e3a…' },
    'ev-perm': { id: 'ev-perm', file: 'Begleitdokumente/Berechtigungsauswertung_2025.xlsx', kind: 'cell', locator: { sheet: 'Berechtigungen', range: 'A7:J7' }, label: 'Incompatible permissions', excerpt: 'MV-U05 can post, run payments, and create vendors.', sha256: 'a85d…' },
    'ev-ledger': { id: 'ev-ledger', file: 'Sachkonten/Sachkontobuchungen.txt', kind: 'rows', locator: { row_start: 20162, row_end: 20186 }, label: 'Net, VAT, and cash trail', excerpt: 'Expense 248000.00 · input VAT 47120.00 · gross cash 295120.00 · user MV-U05', sha256: '265f…' },
    'ev-zero': { id: 'ev-zero', file: 'Begleitdokumente/Wareneingangsliste_2025.csv', kind: 'query', locator: { predicate: 'KREDITOR = 209101', population_count: 858, match_count: 0 }, label: 'No matched goods receipt', excerpt: 'The reproducible filter returned zero matches across the complete receipt population.', sha256: 'e203…' },
    'ev-repair': { id: 'ev-repair', file: 'AV/Anlagen.txt', kind: 'rows', locator: { row_start: 191, row_end: 196 }, label: 'Repair descriptions registered as assets', excerpt: 'Reparatur · Austausch · Instandsetzung · Generalüberholung recorded as new assets.', sha256: 'a031…' },
    'ev-cutoff': { id: 'ev-cutoff', file: 'Begleitdokumente/Fakturajournal_Januar_2026_Kreditoren.csv', kind: 'rows', locator: { row_start: 2, row_end: 9 }, label: 'January invoices for December performance', excerpt: 'Eight invoices total 192000.00 with December performance dates.', sha256: '209f…' },
    'ev-receipts': { id: 'ev-receipts', file: 'Begleitdokumente/Wareneingangsliste_2025.csv', kind: 'rows', locator: { row_start: 842, row_end: 849 }, label: 'Open December goods receipts', excerpt: 'Eight matching receipts were marked Rechnung offen before year-end.', sha256: 'e203…' },
    'ev-split': { id: 'ev-split', file: 'Kreditoren/Lieferantenbuchungen.txt', kind: 'rows', locator: { row_start: 2569, row_end: 2572 }, label: 'Same-day payments below approval threshold', excerpt: '9780.00 · 9820.00 · 9750.00 · 9690.00 EUR on the same day.', sha256: 'fe8d…' },
    'ev-policy': { id: 'ev-policy', file: 'Begleitdokumente/Pruefungsplanung_JET_2025.docx', kind: 'paragraph', locator: { page: 1, paragraph: 5 }, label: 'Payment approval policy', excerpt: 'Payments from EUR 10,000 require a second approval.', sha256: '45db…' },
  },
  findings: [
    {
      id: 'vendor-control-chain', title: 'Probable sham-vendor control chain: Ratio Consulting GmbH',
      category: 'Cash misappropriation', system_status: 'investigate', auditor_status: 'unreviewed', severity: 'critical', confidence: 'high',
      summary: 'One user could create, approve, book, and pay the vendor; the complete receipt population contains no match.',
      amounts: { net: '248000.00', tax: '47120.00', gross: '295120.00', pnl_effect: null },
      facts: [{ label: 'Vendor', value: '209101', evidence_id: 'ev-change' }, { label: 'Creator and approver', value: 'MV-U05', evidence_id: 'ev-change' }, { label: 'Receipt matches', value: '0', evidence_id: 'ev-zero' }],
      caveats: ['Absence of a goods receipt alone does not prove consulting services were not delivered.'],
      next_step: 'Independently confirm service delivery and bank-account ownership.',
      evidence_ids: ['ev-change', 'ev-perm', 'ev-ledger', 'ev-zero'], counter_evidence_ids: [],
      graph: { nodes: [{ id: 'user', label: 'MV-U05', type: 'user' }, { id: 'rights', label: 'Post · create · pay', type: 'permission' }, { id: 'vendor', label: 'Ratio Consulting', type: 'vendor' }, { id: 'invoices', label: '5 invoices', type: 'invoice' }, { id: 'payments', label: '5 payments', type: 'payment' }, { id: 'bank', label: '€295.1k cash', type: 'bank' }], edges: [{ source: 'user', target: 'rights', label: 'holds' }, { source: 'user', target: 'vendor', label: 'created + approved' }, { source: 'vendor', target: 'invoices', label: 'issued' }, { source: 'invoices', target: 'payments', label: 'paid in 2 days' }, { source: 'payments', target: 'bank', label: 'settled' }] },
    },
    {
      id: 'capitalized-repairs', title: 'Repair-like costs capitalized as fixed assets', category: 'Classification / override',
      system_status: 'investigate', auditor_status: 'unreviewed', severity: 'high', confidence: 'medium',
      summary: 'Repair descriptions flow from supplier invoices into newly created fixed assets instead of repair expense.',
      amounts: { net: '150800.00', tax: '28652.00', gross: '179452.00', pnl_effect: '-150800.00' },
      facts: [{ label: 'Potential adjustment', value: '150800.00', evidence_id: 'ev-repair', format: 'currency' }, { label: 'Items', value: '6', evidence_id: 'ev-repair' }],
      caveats: ['Major replacements can qualify for capitalization depending on scope and policy.'], next_step: 'Inspect invoice scope and capitalization policy.',
      evidence_ids: ['ev-repair'], counter_evidence_ids: [],
      graph: { nodes: [{ id: 'invoice', label: '6 repair invoices', type: 'invoice' }, { id: 'asset', label: '6 new assets', type: 'asset' }, { id: 'ledger', label: 'Fixed assets', type: 'account' }], edges: [{ source: 'invoice', target: 'asset', label: 'registered as' }, { source: 'asset', target: 'ledger', label: 'capitalized' }] },
    },
    {
      id: 'year-end-cutoff', title: 'December obligations parked in the next period', category: 'Cut-off / liabilities',
      system_status: 'exception', auditor_status: 'unreviewed', severity: 'high', confidence: 'high',
      summary: 'Goods were received before year-end, while matching invoices appear only in January.',
      amounts: { net: '192000.00', tax: null, gross: null, pnl_effect: '-192000.00' },
      facts: [{ label: 'Unrecorded-liability population', value: '192000.00', evidence_id: 'ev-cutoff', format: 'currency' }, { label: 'Invoices', value: '8', evidence_id: 'ev-cutoff' }],
      caveats: ['The profit effect depends on whether the goods remained in inventory.'], next_step: 'Trace each receipt into inventory consumption.',
      evidence_ids: ['ev-cutoff', 'ev-receipts'], counter_evidence_ids: [],
      graph: { nodes: [{ id: 'receipt', label: '8 December receipts', type: 'receipt' }, { id: 'close', label: 'Year-end close', type: 'control' }, { id: 'invoice', label: '8 January invoices', type: 'invoice' }, { id: 'ledger', label: 'No posting', type: 'journal' }], edges: [{ source: 'receipt', target: 'close', label: 'before' }, { source: 'close', target: 'invoice', label: 'after' }, { source: 'invoice', target: 'ledger', label: 'missing' }] },
    },
    {
      id: 'threshold-splitting', title: 'Payments structured below approval threshold: Castor Papier GmbH', category: 'Control circumvention',
      system_status: 'investigate', auditor_status: 'unreviewed', severity: 'medium', confidence: 'high',
      summary: 'Several same-day payments fall immediately below the sourced two-approval threshold.',
      amounts: { net: null, tax: null, gross: '39040.00', pnl_effect: null },
      facts: [{ label: 'Combined payments', value: '39040.00', evidence_id: 'ev-split', format: 'currency' }, { label: 'Approval threshold', value: '10000.00', evidence_id: 'ev-policy', format: 'currency' }],
      caveats: ['The pattern proves a control indicator, not intent or misstatement.'], next_step: 'Inspect payment proposals and approver logs.',
      evidence_ids: ['ev-split', 'ev-policy'], counter_evidence_ids: [],
      graph: { nodes: [{ id: 'vendor', label: 'Castor Papier', type: 'vendor' }, { id: 'payments', label: '4 same-day payments', type: 'payment' }, { id: 'threshold', label: '€10k threshold', type: 'control' }, { id: 'bank', label: '€39k cash', type: 'bank' }], edges: [{ source: 'vendor', target: 'payments', label: 'received' }, { source: 'payments', target: 'threshold', label: 'each below' }, { source: 'payments', target: 'bank', label: 'combined' }] },
    },
  ],
}
